global:
  scrape_interval: 1s #Scrape interval to every 1 second.
  evaluation_interval: 1s #Evaluate rules every 1 second.
  
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 1s
    static_configs:
      - targets: ["cadvisor:8080"]
